import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Foot-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <h1 className={styles.title}>
          <span className="mySpan">Foot-Blog</span>
        </h1>
        <div className={styles.imagewrap}>
          <Image
            className={styles.myImg}
            src="/home.jpg"
            alt=""
            width={237}
            height={158}
          />
        </div>
        <p className={styles.description}>
          A blog for coders, from a coder with the perspective of a coder
        </p>
        <div className="blogs" style={{ padding: "0 370px" }}>
          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3 align="center">Blog1</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,
              corporis aspernatur est voluptate sed voluptatem fugiat iure quasi
              nihil consequuntur? Beatae fugit voluptate amet mollitia deserunt
              corporis ratione suscipit. Harum!
            </p>
          </div>
          <div className="blogItem">
            <h3 align="center">Blog2</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,
              corporis aspernatur est voluptate sed voluptatem fugiat iure quasi
              nihil consequuntur? Beatae fugit voluptate amet mollitia deserunt
              corporis ratione suscipit. Harum!
            </p>
          </div>
          <div className="blogItem">
            <h3 align="center">Blog3</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,
              corporis aspernatur est voluptate sed voluptatem fugiat iure quasi
              nihil consequuntur? Beatae fugit voluptate amet mollitia deserunt
              corporis ratione suscipit. Harum!
            </p>
          </div>
        </div>
      </main>
      </div>
    </>
  );
}
