import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Foot-Blog</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div className={styles.imagewrap}>
            <img
              className={styles.myImg}
              src="/home.jpg"
              alt="Foot-Blog"
              width={237}
              height={158}
            />
          </div>
          <h1 className={styles.title}>
            <span className="mySpan">🥅 Foot-Blog 🥅</span>
          </h1>
          <p className={styles.description}>
            A blog for coders, from a coder with the perspective of a coder
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laborum
            sequi aliquam doloremque! Odit esse asperiores doloribus, aliquid
            nobis magnam nisi tempora atque in!
          </p>
          <hr className={styles.hr} />
          <div className={styles.blogs}>
            <h2 className={styles.h2}>Latest Blogs</h2>
            <div className={styles.items}>
              <h3 className={styles.h3}>Blog1</h3>
              <p className={styles.p}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Nesciunt, corporis aspernatur est voluptate sed voluptatem
                fugiat iure quasi nihil consequuntur? Beatae fugit voluptate
                amet mollitia deserunt corporis ratione suscipit. Harum!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.items}>
              <h3 className={styles.h3}>Blog2</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Nesciunt, corporis aspernatur est voluptate sed voluptatem
                fugiat iure quasi nihil consequuntur? Beatae fugit voluptate
                amet mollitia deserunt corporis ratione suscipit. Harum!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
            <div className={styles.items}>
              <h3 className={styles.h3}>Blog3</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Nesciunt, corporis aspernatur est voluptate sed voluptatem
                fugiat iure quasi nihil consequuntur? Beatae fugit voluptate
                amet mollitia deserunt corporis ratione suscipit. Harum!
              </p>
              <button className={styles.btn}>Read More</button>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
